#
# Versión 2.0
# Fecha: 12 de noviembre de 2025
#
# Autores: Helena Ruiz Ramírez
# Función: Instrucciones para desplegar la aplicación de exports con Docker
#
# Usa una imagen oficial de Python como imagen base
FROM python:3.13.7

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requerimientos, osea las librerias que utilisa el programa
COPY docker/requirements_export.txt .

# Instalar los paquetes necesarios
RUN pip install --no-cache-dir -r requirements_export.txt

# Crea los directorios necesarios para la aplicación
RUN mkdir -p export-to-sheets utils

# Copia el contenido de la aplicación
COPY export-to-sheets/ ./export-to-sheets/
COPY utils/ ./utils/

# Hace que el puerto 8080 esté disponible
EXPOSE 8080

# Define la variable de entorno para el puerto
ENV PORT=8080

ENV STREAMLIT_SERVER_HEADLESS=true \
    STREAMLIT_SERVER_PORT=8080 \
    STREAMLIT_SERVER_ADDRESS=0.0.0.0 \
    STREAMLIT_SERVER_ENABLECORS=false \
    STREAMLIT_SERVER_ENABLEXSRFPROTECTION=true \
    STREAMLIT_SERVER_ENABLEWEBSOCKETCOMPRESSION=false \
    STREAMLIT_BROWSER_GATHER_USAGE_STATS=false

# Le dice a la aplicación que considere el path completo (no solo /export-to-sheets) al correr
ENV PYTHONPATH="/app"

# Ejecuta la aplicación streamlit cuando el contenedor se inicie
CMD ["bash", "-lc", "\
    streamlit run export-to-sheets/streamlit_app.py \
    --server.port=${PORT:-8080} \
    --server.address=0.0.0.0 \
    --server.headless=true \
    --server.enableCORS=false \
    --server.runOnSave=false \
    --logger.level=info"]