# Usa una imagen oficial de Python como imagen base
FROM python:3.9-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo de requerimientos, osea las librerias que utilisa el programa
COPY docker/requirements_export.txt .

# Instalar los paquetes necesarios
RUN pip install --no-cache-dir -r requirements_export.txt

# Crea los directorios necesarios para la aplicación
RUN mkdir -p export-to-sheets utils

# Copia los archivos específicos de la aplicación a sus respectivos directorios
COPY scripts/export-to-sheets/enum_equipos.py export-to-sheets/
COPY scripts/export-to-sheets/enum_unidades.py export-to-sheets/
COPY scripts/export-to-sheets/format_convos.py export-to-sheets/
COPY scripts/export-to-sheets/google_auth.py export-to-sheets/
COPY scripts/export-to-sheets/pull_convos.py export-to-sheets/
COPY scripts/export-to-sheets/streamlit_app.py export-to-sheets/
COPY scripts/export-to-sheets/upload_convos.py export-to-sheets/
COPY scripts/utils/liveconnect_api.py utils/

# Hace que el puerto 8501 esté disponible
EXPOSE 8501

# Define la variable de entorno para el puerto
ENV PORT 8501

# Ejecuta la aplicación streamlit cuando el contenedor se inicie
CMD ["streamlit", "run", "scripts/export-to-sheets/streamlit_app.py", "--server.port", "8501", "--server.enableCORS", "false"]